export const DIFFICULTIES = {
  easy: {
    label: "Easy",
    enemyHpMultiplier: 0.6,
    playerDamageTakenMultiplier: 0.5,
    healthPickupMultiplier: 1.5,
    motionTrackerRange: 20,
    shamblerMoanRadius: 12,
    crawlerSpeed: 5.5,
    ammoPickupMultiplier: 1.2,
    allowManualSave: true,
  },
  normal: {
    label: "Normal",
    enemyHpMultiplier: 1.0,
    playerDamageTakenMultiplier: 1.0,
    healthPickupMultiplier: 1.0,
    motionTrackerRange: 14,
    shamblerMoanRadius: 12,
    crawlerSpeed: 5.5,
    ammoPickupMultiplier: 1.0,
    allowManualSave: true,
  },
  hard: {
    label: "Hard",
    enemyHpMultiplier: 1.4,
    playerDamageTakenMultiplier: 1.6,
    healthPickupMultiplier: 0.8,
    motionTrackerRange: 10,
    shamblerMoanRadius: 18,
    crawlerSpeed: 6.5,
    ammoPickupMultiplier: 0.5,
    allowManualSave: false,
  },
};

export const GAME_CONFIG = {
  renderer: {
    exposure: 3.0,
    ssaoRadius: 0.35,
    ssaoIntensity: 0.025,
    bloomStrength: 0.5,
    bloomRadius: 0.45,
    bloomThreshold: 0.78,
  },
  player: {
    eyeHeight: 1.75,
    capsuleRadius: 0.35,
    moveSpeed: 5.1,
    crouchSpeedFactor: 0.6,
    crouchHeightDrop: 0.4,
    fov: 75,
    adsFov: 55,
    adsTransitionMs: 80,
    headBobAmplitude: 0.04,
    headBobFrequencyHz: 8,
    sprintSpeedMultiplier: 1.68,
    sprintFov: 82,
    maxShield: 50,
    shieldRechargeDelay: 4.0,
    shieldRechargeRate: 15,
    meleeDamage: 45,
    meleeRange: 1.7,
    meleeCooldown: 0.85,
  },
  weapons: {
    ar: {
      id: "ar",
      name: "MA5 Assault Rifle",
      damage: 28,
      magSize: 30,
      reserveMax: 180,
      fireInterval: 0.09,
      reloadTime: 2.0,
      hipSpreadDeg: 3.0,
      adsSpreadDeg: 1.1,
      falloffStart: 24,
      falloffEnd: 55,
      falloffMinMultiplier: 0.65,
      canAds: true,
    },
    m6d: {
      id: "m6d",
      name: "M6D Magnum",
      damage: 90,
      magSize: 12,
      reserveMax: 72,
      fireInterval: 0.18,
      reloadTime: 1.6,
      hipSpreadDeg: 2.5,
      adsSpreadDeg: 0.0,
      falloffStart: 18,
      falloffEnd: 40,
      falloffMinMultiplier: 0.4,
      canAds: true,
    },
    shotgun: {
      id: "shotgun",
      name: "M90 Shotgun",
      damage: 14,
      pellets: 9,
      magSize: 8,
      reserveMax: 48,
      fireInterval: 0.35,
      reloadTime: 0.5,
      hipSpreadDeg: 7.5,
      adsSpreadDeg: 5.0,
      falloffStart: 10,
      falloffEnd: 26,
      falloffMinMultiplier: 0.35,
      canAds: false,
    },
    plasma: {
      id: "plasma",
      name: "Plasma Rifle",
      damage: 12,
      burstCount: 4,
      burstInterval: 0.08,
      magSize: 30,
      overheatThreshold: 24,
      cooldown: 2.5,
      burstResetDelay: 1.5,
    },
    grenade: {
      id: "grenade",
      name: "Grenade Launcher",
      damage: 140,
      radius: 2.5,
      magSize: 4,
      reserveMax: 0,
      pumpTime: 0.8,
      projectileSpeed: 12,
    },
    sniper: {
      id: "sniper",
      name: "SRS99 Sniper Rifle",
      damage: 265,
      magSize: 4,
      reserveMax: 16,
      fireInterval: 0.0,
      reloadTime: 3.2,
      hipSpreadDeg: 4.5,
      adsSpreadDeg: 0.0,
      falloffStart: 80,
      falloffEnd: 220,
      falloffMinMultiplier: 0.75,
      canAds: true,
      adsFov: 20,
      pumpTime: 1.1,
    },
  },
  enemyStats: {
    shamblerLab: {
      hp: 40,
      bodyDamage: 30,
      speedSlow: 0.95,
      speedLurch: 2.25,
      attackCooldown: 0.8,
      headHeight: 1.42,
    },
    shamblerGuard: {
      hp: 70,
      bodyDamage: 30,
      speedSlow: 0.9,
      speedLurch: 2.1,
      attackCooldown: 0.8,
      headHeight: 1.48,
    },
    crawler: {
      hp: 35,
      walkSpeed: 2.2,
      sprintSpeed: 5.5,
      sprintRange: 8,
      swipeRange: 1.2,
      swipeDamage: 25,
      swipeDelay: 0.3,
      comboCooldown: 1.0,
      reanimateDuration: 4,
      freshCorpseWindow: 20,
      headHeight: 1.28,
    },
    brute: {
      hp: 330,
      speed: 1.8,
      haymakerDamage: 65,
      haymakerRange: 1.8,
      haymakerWindup: 0.7,
      haymakerMissRecovery: 0.4,
      shoveDamage: 25,
      shoveRange: 1.4,
      shoveKnockback: 2.0,
      shoveStun: 0.4,
      grabRange: 1.0,
      grabThresholdHpRatio: 0.3,
      grabDuration: 1.5,
      grabTickDamage: 20,
      grabTickInterval: 0.5,
      grabBreakStagger: 0.6,
      headHeight: 1.95,
    },
    reanimated: {
      hp: 25,
      bodyDamage: 20,
      speedSlow: 2.2,
      speedLurch: 2.8,
      attackCooldown: 1.2,
      headHeight: 1.2,
    },
  },
  gameplayTuning: {
    locationalDamage: {
      multipliers: {
        head: 1.95,
        neck: 1.45,
        upperTorso: 1.0,
        lowerTorso: 0.88,
        arm: 0.7,
        leg: 0.62,
      },
      perType: {
        brute: {
          head: 1.6,
          neck: 1.28,
          upperTorso: 0.94,
          arm: 0.66,
          leg: 0.55,
        },
        crawler: {
          head: 1.85,
          neck: 1.42,
          arm: 0.75,
          leg: 0.68,
        },
      },
    },
    spawnSpacing: {
      spacingScaleByDifficulty: {
        easy: 1.22,
        normal: 1.0,
        hard: 0.9,
      },
      intraGroupMultiplier: {
        default: 1.2,
        brute: 1.35,
      },
      fallbackSpreadBonus: 0.8,
      fallbackDistanceBonus: 0.15,
      enemyPadding: {
        default: 0.65,
        crawler: 0.55,
        brute: 1.0,
      },
      minSpawnSpacing: {
        default: 0.32,
        crawler: 0.34,
        brute: 0.85,
      },
    },
    deaths: {
      explodeThreshold: {
        defaultOverkill: 0.95,
        defaultFatal: 0.5,
        bruteOverkill: 1.2,
        bruteFatal: 0.65,
      },
      dismemberChance: {
        precisionShotgunHeadshot: 0.88,
        heavyKillDefault: 0.72,
        heavyKillBrute: 0.78,
        legBias: 0.68,
      },
      randomGibChance: {
        default: 0.28,
        brute: 0.03,
      },
    },
  },
  keyColors: {
    blue: 0x0044ff,
    green: 0x00bb44,
    orange: 0xff6600,
    red: 0xff1111,
  },
};

export const MATERIAL_PRESETS = {
  wall: {
    color: 0x555e6a,
    metalness: 0.6,
    roughness: 0.75,
  },
  floor: {
    color: 0x555e6a,
    metalness: 0.6,
    roughness: 0.75,
  },
  ceiling: {
    color: 0x49515e,
    metalness: 0.5,
    roughness: 0.8,
  },
  alien: {
    color: 0x1a2a14,
    emissive: 0x4a7a3a,
    emissiveIntensity: 0.55,
    metalness: 0.1,
    roughness: 0.9,
  },
  glass: {
    color: 0xa0c8ff,
    transmission: 0.9,
    roughness: 0.05,
  },
};

export const STORAGE_KEY = "alienx-save-slot-v1";

/** Per-weapon muzzle flash point light color. */
export const WEAPON_FLASH_COLORS = {
  ar: 0xffe8a0,
  m6d: 0xfff0c0,
  shotgun: 0xff9040,
  plasma: 0x60ffee,
  grenade: 0xff6820,
  sniper: 0xffffff,
};
